#!/bin/bash

echo "══════════════════════════════════════════════════════════════"
echo "        DARKZSAID VPS MANAGER - ARCHIVO PRINCIPAL"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "[OK] carrasco se ejecutó correctamente."
echo "[INFO] Sistema detectado:"
grep PRETTY_NAME /etc/os-release
echo ""
echo "Instalación principal finalizada correctamente."
